from __future__ import annotations

"""Base abstractions for controller-side clients and movement dispatch.
It defines:

- ``MovementManager``: an abstract dispatcher that maps movement commands to
  concrete callables.
- ``MovementController``: an abstract client wrapper that plugs controller
  callbacks into ``drone_system.Client``.

Concrete controller implementations are expected to subclass these base
classes and provide the movement dispatch logic together with data generation
and processing callbacks.
"""

import abc
import drone_system
import typing
import func_decorators


class BaseMovementManager(abc.ABC):
    """Abstract command dispatcher for controller-issued movement actions.

    Parameters
    ----------
    dispatch:
        Mapping of command identifiers to callables or handler objects that
        know how to execute a movement request.
    """

    def __init__(self, dispatch: dict[typing.Hashable, typing.Any]) -> None:
        self.moves: list[typing.Any] = list(dispatch.keys())
        self.dispatch_table: dict[typing.Hashable, typing.Any] = dispatch
    
    @abc.abstractmethod
    def dispatch_movement(self, move: typing.Any, *args: tuple, **kwargs: dict[str, typing.Any]):
        """Execute one movement command using the underlying dispatch table."""
        ...


class BaseMovementController(abc.ABC):
    """Base class for controller clients connected to ``drone_system``.

    A movement controller wraps two callbacks:

    - a generating callback used to publish controller-originated data
    - a processing callback used to handle inbound messages

    If custom callables are not provided, subclasses must implement the
    default ``generate_controller_data`` and ``process_controller_data``
    methods.
    """

    def __init__(self,
                 controller_id: str,
                 data_receivers: list[str],
                 movement_manager: BaseMovementManager,
                 gen_func: typing.Callable | None = None,
                 proc_func: typing.Callable| None = None) -> None:
        """Initialize the controller client and register its callbacks.

        Parameters
        ----------
        controller_id:
            Identifier used when registering the controller with the shared
            communication system.
        data_receivers:
            Client identifiers that should receive messages generated by this
            controller.
        movement_manager:
            Dispatcher responsible for translating movement commands into
            concrete actions.
        gen_func:
            Optional override for outbound message generation.
        proc_func:
            Optional override for inbound message processing.
        """
        self.gen_func: typing.Callable = gen_func if gen_func is not None else self.generate_controller_data
        self.proc_func: typing.Callable = proc_func if proc_func is not None else self.process_controller_data
        self.data_receivers: list[str] = data_receivers

        self.movement_dispatch_manager: BaseMovementManager = movement_manager

        self.client_instance: drone_system.Client = drone_system.Client(
            controller_id, self.gen_func, self.proc_func, True
        )

    @func_decorators.generating_func
    def generate_controller_data(self) -> dict[str, typing.Any]:
        """Build one outbound message for the controller.

        Subclasses can implement this when the controller needs to periodically
        publish state into the communication system.
        """
        raise NotImplementedError("Controller function for generating data is not implemented")

    @func_decorators.processing_func
    def process_controller_data(self, message: dict[str, typing.Any]) -> None:
        """Handle one inbound message addressed to this controller."""
        raise NotImplementedError("Controller function for processing data is not implemented")